name: Feature Request
description: Request a new or improved a feature in Analog
labels: [enhancement]

body:
  - type: markdown
    attributes:
      value: |
          Please search GitHub for a similar [issue](https://github.com/projectbay/os-projectbay/issues) or [PR](https://github.com/projectbay/os-projectbay/issues)  before submitting a new issue.
  - type: dropdown
    id: type_bug
    attributes:
      label: Which scope/s are relevant/related to the feature request?
      options:
        - ngx-mat-shell
        - ngx-mat-shell docs
        - ngx-mat-shell demo
    validations:
      required: true

  - type: textarea
    id: information
    attributes:
      label: Information
      description: Tell us what you want to be added to os-projectbay
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Describe any alternatives/workarounds you're currently using

  - type: checkboxes
    id: assistance
    attributes:
      label: I would be willing to submit a PR to fix this issue
      description: Assistance is provided if you need help submitting a pull request
      options:
        - label: 'Yes'
        - label: 'No'