name: release-ngx-mat-shell

on:
  - workflow_dispatch

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.14.0'
      - uses: pnpm/action-setup@v2
        with:
          version: 8.12.1
      - name: Setup Git
        run: |
          git config user.name "GitHub Bot"
          git config user.email "gituser@example.com"
      - name: Installing
        run: pnpm install --frozen-lockfile
      - name: Version
        shell: bash
        run: npx nx run ngx-mat-shell:version
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Tag main
        shell: bash
        run: |
          git tag -f main
          git push origin main --force
